spring:
    application:
        name: spring-ai-rag
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            embedding:
              options:
                model: text-embedding-3-small
tjr:
    aiapp:
        vectorStorePath: /tmp/vectorstore.json
        documentsToLoad:
            - classpath:/movies500.csv